import { StyleSheet } from 'react-native';

export const colors = {
  navy: '#142D52',
  blue: '#2363B4',
  teal: '#009187',
  orange: '#E67E22',
  green: '#18895B',
  red: '#C63C4C',
  ink: '#1F2937',
  muted: '#667085',
  line: '#D9E1EA',
  canvas: '#EEF3F8',
  white: '#FFFFFF',
  softBlue: '#EAF3FF',
  softTeal: '#E7F7F4',
  softOrange: '#FFF3E6',
};

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  full: { width: '100%' },
  pressed: { opacity: 0.78 },
  stage: { flex: 1, backgroundColor: '#D9E2EC', alignItems: 'center' },
  phone: {
    flex: 1,
    width: '100%',
    maxWidth: 480,
    backgroundColor: colors.canvas,
    overflow: 'hidden',
  },
  page: { flexGrow: 1, paddingHorizontal: 20, paddingTop: 24, paddingBottom: 36 },
  logo: {
    width: 94,
    height: 94,
    borderRadius: 26,
    backgroundColor: colors.navy,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    marginTop: 28,
    marginBottom: 24,
  },
  logoSmall: { color: '#A8D8FF', fontSize: 13, fontWeight: '800', letterSpacing: 1.8 },
  logoBig: { color: colors.white, fontSize: 29, fontWeight: '900' },
  loginTitle: {
    color: colors.navy,
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '800',
    textAlign: 'center',
  },
  loginCopy: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 24,
  },
  card: {
    backgroundColor: colors.white,
    borderRadius: 22,
    padding: 22,
    borderWidth: 1,
    borderColor: '#E5EAF0',
    elevation: 2,
  },
  cardTitle: { color: colors.ink, fontSize: 20, fontWeight: '800', marginBottom: 6 },
  label: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '700',
    marginTop: 17,
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#F8FAFC',
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 13,
    minHeight: 50,
    paddingHorizontal: 15,
    color: colors.ink,
    fontSize: 15,
  },
  area: { minHeight: 118, paddingTop: 14, paddingBottom: 14 },
  helper: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 6 },
  error: { color: colors.red, fontSize: 13, lineHeight: 18, marginTop: 10 },
  button: {
    minHeight: 52,
    borderRadius: 14,
    backgroundColor: colors.blue,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    paddingHorizontal: 18,
  },
  buttonLight: { backgroundColor: colors.white },
  buttonText: { color: colors.white, fontSize: 16, fontWeight: '800' },
  buttonTextLight: { color: colors.navy },
  outlineButton: {
    minHeight: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  outlineText: { color: colors.navy, fontSize: 15, fontWeight: '800' },
  centerLink: {
    color: colors.blue,
    fontSize: 14,
    fontWeight: '700',
    textAlign: 'center',
    marginTop: 17,
  },
  prototype: {
    color: '#8996A8',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.2,
    textAlign: 'center',
    marginTop: 22,
  },
  topRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  eyebrow: {
    color: colors.teal,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 1.4,
    marginBottom: 4,
  },
  greeting: { color: colors.navy, fontSize: 27, fontWeight: '800' },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: colors.navy,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: { color: colors.white, fontWeight: '900' },
  hero: {
    backgroundColor: colors.navy,
    borderRadius: 24,
    padding: 22,
    marginTop: 22,
    marginBottom: 24,
  },
  plusBox: {
    width: 48,
    height: 48,
    borderRadius: 15,
    backgroundColor: colors.teal,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  plus: { color: colors.white, fontSize: 31, lineHeight: 34 },
  heroTitle: { color: colors.white, fontSize: 22, fontWeight: '800' },
  heroCopy: { color: '#C8D8EA', fontSize: 14, marginTop: 7 },
  section: {
    color: colors.navy,
    fontSize: 18,
    fontWeight: '800',
    marginTop: 7,
    marginBottom: 13,
  },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  link: { color: colors.blue, fontSize: 14, fontWeight: '700' },
  stats: { flexDirection: 'row', gap: 9 },
  stat: {
    flex: 1,
    backgroundColor: colors.white,
    borderRadius: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#E7ECF2',
  },
  statValue: { fontSize: 24, fontWeight: '900' },
  statLabel: { color: colors.muted, fontSize: 11, fontWeight: '700', marginTop: 3 },
  reportCard: {
    backgroundColor: colors.white,
    borderRadius: 18,
    padding: 17,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E3E9F0',
    elevation: 1,
  },
  reportId: { color: colors.muted, fontSize: 12, fontWeight: '800' },
  reportTitle: {
    color: colors.ink,
    fontSize: 17,
    fontWeight: '800',
    marginTop: 10,
    marginBottom: 7,
  },
  reportMeta: { color: colors.muted, fontSize: 13 },
  reportDate: { color: '#8A95A5', fontSize: 12, marginTop: 12 },
  arrow: { color: colors.blue, fontSize: 27, marginTop: 4 },
  badge: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  badgeText: { fontSize: 11, fontWeight: '800' },
  nav: {
    marginTop: 16,
    backgroundColor: colors.white,
    borderRadius: 22,
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    borderWidth: 1,
    borderColor: '#E1E8EF',
  },
  navItem: { minWidth: 82, alignItems: 'center', paddingVertical: 10 },
  navIcon: { color: colors.muted, fontSize: 22 },
  navLabel: { color: colors.muted, fontSize: 11, fontWeight: '700' },
  navActive: { color: colors.blue },
  navCreate: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: colors.blue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  navCreateText: { color: colors.white, fontSize: 29 },
  header: { flexDirection: 'row', alignItems: 'center', gap: 13, marginBottom: 20 },
  back: {
    width: 43,
    height: 43,
    borderRadius: 14,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.line,
  },
  backText: { color: colors.navy, fontSize: 24 },
  pageTitle: { color: colors.navy, fontSize: 24, fontWeight: '800' },
  subtitle: { color: colors.muted, fontSize: 13, marginTop: 2 },
  progressWrap: { marginBottom: 8 },
  progressTrack: {
    height: 6,
    borderRadius: 99,
    backgroundColor: '#DCE5EF',
    overflow: 'hidden',
  },
  progressFill: { height: '100%', backgroundColor: colors.teal },
  progressText: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'right',
    marginTop: 6,
  },
  choiceGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9 },
  choice: {
    width: '48%',
    minHeight: 55,
    borderRadius: 14,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderColor: colors.line,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 13,
  },
  choiceActive: { borderColor: colors.blue, backgroundColor: colors.softBlue },
  dot: {
    width: 13,
    height: 13,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#AAB4C2',
    marginRight: 9,
  },
  dotActive: { borderColor: colors.blue, backgroundColor: colors.blue },
  choiceText: { color: colors.ink, fontSize: 12, fontWeight: '700', flexShrink: 1 },
  choiceTextActive: { color: colors.blue },
  chipRow: { flexDirection: 'row', gap: 4 },
  chip: {
    backgroundColor: colors.white,
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 99,
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginRight: 7,
  },
  chipActive: { backgroundColor: colors.navy, borderColor: colors.navy },
  chipText: { color: colors.muted, fontSize: 13, fontWeight: '700' },
  chipTextActive: { color: colors.white },
  locationLink: { color: colors.teal, fontSize: 13, fontWeight: '800', marginTop: 11 },
  photo: {
    minHeight: 156,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#AEBBC9',
    borderRadius: 18,
    backgroundColor: '#F8FAFC',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
  },
  photoActive: { borderColor: colors.teal, backgroundColor: colors.softTeal },
  camera: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: colors.navy,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  cameraActive: { backgroundColor: colors.teal },
  cameraText: { color: colors.white, fontSize: 13, fontWeight: '900' },
  photoTitle: { color: colors.ink, fontSize: 15, fontWeight: '800' },
  successPage: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 24 },
  successCircle: {
    width: 88,
    height: 88,
    borderRadius: 30,
    backgroundColor: colors.teal,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 22,
  },
  successCheck: { color: colors.white, fontSize: 48, fontWeight: '800' },
  successTitle: { color: colors.navy, fontSize: 28, fontWeight: '900' },
  successCopy: {
    color: colors.muted,
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 22,
  },
  ticket: {
    width: '100%',
    backgroundColor: colors.white,
    borderRadius: 20,
    padding: 21,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.line,
  },
  ticketLabel: { color: colors.muted, fontSize: 10, fontWeight: '900', letterSpacing: 1.3 },
  ticketId: { color: colors.blue, fontSize: 25, fontWeight: '900', marginTop: 4 },
  divider: { height: 1, backgroundColor: colors.line, width: '100%', marginVertical: 16 },
  ticketTitle: { color: colors.ink, fontSize: 16, fontWeight: '800', marginBottom: 11 },
  addButton: {
    width: 45,
    height: 45,
    borderRadius: 15,
    backgroundColor: colors.blue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addText: { color: colors.white, fontSize: 28 },
  filterBar: { marginVertical: 18, flexGrow: 0 },
  detailCard: {
    backgroundColor: colors.white,
    borderRadius: 22,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.line,
    marginBottom: 22,
  },
  category: { color: colors.teal, fontSize: 12, fontWeight: '900', textTransform: 'uppercase' },
  detailTitle: { color: colors.navy, fontSize: 22, lineHeight: 28, fontWeight: '900', marginTop: 13 },
  detailCopy: { color: colors.muted, fontSize: 14, lineHeight: 21, marginTop: 9 },
  meta: { borderTopWidth: 1, borderTopColor: '#ECF0F4', paddingTop: 11, marginTop: 11 },
  metaLabel: { color: '#8995A6', fontSize: 9, fontWeight: '900', letterSpacing: 1 },
  metaValue: { color: colors.ink, fontSize: 13, fontWeight: '700', marginTop: 4 },
  timeline: { flexDirection: 'row', minHeight: 68 },
  rail: { width: 38, alignItems: 'center' },
  timelineDot: {
    width: 24,
    height: 24,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#BBC5D1',
    backgroundColor: colors.canvas,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineDone: { backgroundColor: colors.teal, borderColor: colors.teal },
  timelineCheck: { color: colors.white, fontSize: 12, fontWeight: '900' },
  line: { width: 2, flex: 1, backgroundColor: '#C9D2DC' },
  lineDone: { backgroundColor: colors.teal },
  timelineCopy: { flex: 1, paddingBottom: 18 },
  timelineTitle: { color: colors.ink, fontSize: 14, fontWeight: '800' },
  evidencePreview: {
    minHeight: 120,
    borderRadius: 17,
    backgroundColor: colors.navy,
    alignItems: 'center',
    justifyContent: 'center',
  },
  evidenceText: { color: '#CDE0F3', fontSize: 11, fontWeight: '900', letterSpacing: 1.2 },
});
